=== SafirSDK/safir-sdk-core/src/dots/dots_v.ss/data/dots_unit.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- Copyright (c) 2004 Saab AB, Sweden

Abstract
The schema defining the unit definitions.

Log
2004-12-25 HESU Created. 
2005-01-14 HESU Removed <dependencies> and <lib>
            moved <class> and <property> to root level.
2005-04-25 HESU Added enumeration, constantArray and constants of any type.
2005-10-23 HESU Changed Element -> Member, Constant -> Parameter, removed stTypeId (replaced by stFullClassName),
            added full parameter definition, made instances optional, made parameter values optional (signalling NULL), defined
            parameter references (recursively).
            Added the Exception element.
            Added the propertyMapping element.
2005-12-01 STLRHA Removed 'minOccurs="0" maxOccurs="unbounded"' propertyMember element in ctMappingMember, since that element 
            should be in there once only.
-->
<xsd:schema targetNamespace="urn:safir-dots-unit" elementFormDefault="qualified"
    xmlns:tns="urn:safir-dots-unit" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- 
    
    Overview:
        <class>, <property> <enumeration> <object> and <exception> are the root elements.
            
-->
    <xsd:simpleType name="stUnitName">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
            <xsd:maxLength value="100" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stClassName">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
            <xsd:maxLength value="100" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stFullClassName">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
            <xsd:maxLength value="100" /><!--aer inte detta lite kort?! -->
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stFullParameterName">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
            <xsd:maxLength value="100" /><!-- aer inte detta lite kort?! -->
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stMemberName">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
            <xsd:maxLength value="100" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stParameterName">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
            <xsd:maxLength value="100" /><!-- aer inte detta lite kort?! -->
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stEnumerationValue">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
            <xsd:maxLength value="100" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stType">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
            <xsd:maxLength value="100" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stArraySize">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stArray">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="0" />
            <xsd:maxLength value="0" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="stStringLength">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="ctEntityId">
        <xsd:sequence>
            <xsd:element name="name" type="tns:stFullClassName" /><!-- Boer inte denna kunna vara en int64 ocksaa? Foer att i framtiden kunna skicka runt typer som en viss nod inte kaenner till? -->
            <xsd:choice minOccurs="1"> <!-- Maaste alltid vara satt numera, eller hur? -->
               <xsd:element name="instanceId" type="xsd:string" />
               <xsd:element name="instanceIdRef" type="tns:ctReference" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctParameterArrayElement">
        <xsd:sequence>
            <xsd:choice minOccurs="0" >
               <xsd:element name="index" type="xsd:integer" />
               <xsd:element name="indexRef" type="tns:ctReference" />
            </xsd:choice>
            <xsd:choice minOccurs="0">
                <xsd:element name="value" type="xsd:string" />
                <xsd:element name="valueRef" type="tns:ctReference" />
                <xsd:element name="object" type="tns:ctObject" />
                <xsd:element name="entityId" type="tns:ctEntityId" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctParameterArray">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="arrayElement" type="tns:ctParameterArrayElement" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctReference">
        <xsd:sequence>
            <xsd:element name="name" type="tns:stFullParameterName" />
            <xsd:choice minOccurs="0" >
               <xsd:element name="index" type="xsd:integer" />
               <xsd:element name="indexRef" type="tns:ctReference" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctObjectMember">
        <xsd:sequence>
            <xsd:element name="name" type="tns:stMemberName" />
            <xsd:choice minOccurs="0">
                <xsd:element name="value" type="xsd:string" />
                <xsd:element name="valueRef" type="tns:ctReference" />
                <xsd:element name="object" type="tns:ctObject" />
                <xsd:element name="entityId" type="tns:ctEntityId" />
                <xsd:element name="arrayElements" type="tns:ctParameterArray" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctObjectMembers">
        <xsd:sequence>
            <xsd:element name="member" type="tns:ctObjectMember" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctObject">
        <xsd:sequence>
            <xsd:element name="name" type="tns:stFullClassName" />
            <xsd:element name="members" type="tns:ctObjectMembers" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctParameter">
        <xsd:sequence>
            <xsd:element name="summary" type="xsd:string" minOccurs="0"  />
            <xsd:element name="name" type="tns:stMemberName" />
            <xsd:element name="type" type="tns:stType" />
            <xsd:choice minOccurs="0">
                <xsd:element name="value" type="xsd:string" />
                <xsd:element name="valueRef" type="tns:ctReference" />
                <xsd:element name="object" type="tns:ctObject" />
                <xsd:element name="entityId" type="tns:ctEntityId" />
                <xsd:element name="arrayElements" type="tns:ctParameterArray" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctParameters">
        <xsd:sequence>
            <xsd:element name="parameter" type="tns:ctParameter" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctMember">
        <xsd:sequence>
            <xsd:element name="summary" type="xsd:string" minOccurs="0"  />
            <xsd:element name="name" type="tns:stMemberName" />
            <xsd:choice  minOccurs="0" >
                 <xsd:element name="arraySize" type="tns:stArraySize" />
                 <xsd:element name="arraySizeRef" type="tns:ctReference" />
                 <xsd:element name="array" type="tns:stArray" />
            </xsd:choice>
            <xsd:element name="type" type="tns:stType" />
            <xsd:choice  minOccurs="0" >
                <xsd:element name="maxLength" type="tns:stStringLength" />
                <xsd:element name="maxLengthRef" type="tns:ctReference" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctMembers">
        <xsd:sequence>
            <xsd:element name="member" type="tns:ctMember" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctCreateParameters">
        <xsd:sequence>
            <xsd:element name="member" type="tns:stMemberName" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctCreateValue">
        <xsd:sequence>
            <xsd:element name="member" type="tns:stMemberName" />
            <xsd:element name="parameter" type="tns:stFullParameterName" />
            <xsd:element name="index" type="xsd:integer" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctCreateValues">
        <xsd:sequence>
            <xsd:element name="value" type="tns:ctCreateValue" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctCreateRoutine">
        <xsd:sequence>
            <xsd:element name="summary" type="xsd:string" minOccurs="0"  />
            <xsd:element name="name" type="tns:stMemberName" />
            <xsd:element name="parameters" type="tns:ctCreateParameters" minOccurs="0"  />
            <xsd:element name="values" type="tns:ctCreateValues" minOccurs="0"  />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctCreateRoutines">
        <xsd:sequence>
            <xsd:element name="createRoutine" type="tns:ctCreateRoutine" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctEnumerationValues">
        <xsd:sequence>
            <xsd:element name="value" type="tns:stEnumerationValue" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctClass">
        <xsd:sequence>
            <xsd:element name="summary" type="xsd:string" minOccurs="0"  />
            <xsd:element name="name" type="tns:stUnitName" />
            <xsd:element name="baseClass" type="tns:stFullClassName" />
            <xsd:element name="parameters" type="tns:ctParameters" minOccurs="0" />
            <xsd:element name="members" type="tns:ctMembers" minOccurs="0" />
            <xsd:element name="createRoutines" type="tns:ctCreateRoutines" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctException">
        <xsd:sequence>
            <xsd:element name="summary" type="xsd:string" minOccurs="0"  />
            <xsd:element name="name" type="tns:stUnitName" />
            <xsd:element name="baseClass" type="tns:stFullClassName" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctProperty">
        <xsd:sequence>
            <xsd:element name="summary" type="xsd:string" minOccurs="0"  />
            <xsd:element name="name" type="tns:stUnitName" />
            <xsd:element name="members" type="tns:ctMembers" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctEnumeration">
        <xsd:sequence>
            <xsd:element name="summary" type="xsd:string" minOccurs="0"  />
            <xsd:element name="name" type="tns:stUnitName" />
            <xsd:element name="values" type="tns:ctEnumerationValues" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctMappingReference">
        <xsd:sequence>
            <xsd:element name="classMember" type="tns:stMemberName" />
            <xsd:choice minOccurs="0" >
               <xsd:element name="index" type="xsd:integer" />
               <xsd:element name="indexRef" type="tns:ctReference" />
            </xsd:choice>
            <xsd:element name="classMemberReference" type="tns:ctMappingReference" minOccurs="0"  />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctMappingMember">
        <xsd:sequence>
            <xsd:element name="propertyMember" type="tns:stMemberName" />
            <xsd:choice minOccurs="0">
                <xsd:element name="classMemberReference" type="tns:ctMappingReference" />
                <xsd:element name="value" type="xsd:string" />
                <xsd:element name="valueRef" type="tns:ctReference" />
                <xsd:element name="object" type="tns:ctObject" />
                <xsd:element name="entityId" type="tns:ctEntityId" />
                <xsd:element name="arrayElements" type="tns:ctParameterArray" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctMappingMembers">
        <xsd:sequence>
            <xsd:element name="member" type="tns:ctMappingMember" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ctPropertyMapping">
        <xsd:sequence>
            <xsd:element name="summary" type="xsd:string" minOccurs="0"  />
            <xsd:element name="property" type="tns:stFullClassName" />
            <xsd:element name="class" type="tns:stFullClassName" />
            <xsd:element name="memberMapping" type="tns:ctMappingMembers" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="class" type="tns:ctClass">
        <!--
        The root element defining a Class.
    --></xsd:element>
    <xsd:element name="exception" type="tns:ctException">
        <!--
        The root element defining a Class.
    --></xsd:element>
    <xsd:element name="property" type="tns:ctProperty">
        <!--
        The root element defining a Property.
    --></xsd:element>
    <xsd:element name="enumeration" type="tns:ctEnumeration">
        <!--
        The root element defining an Enumeration.
    --></xsd:element>
    <xsd:element name="object" type="tns:ctObject">
        <!--
        The root element defining an Object. This is used for serialized objects.
        It is not to be used as root element in dou-files.
    --></xsd:element>
    <xsd:element name="propertyMapping" type="tns:ctPropertyMapping">
        <!--
        The root element defining a PropertyMapping, this is to be used in .dom files
    --></xsd:element>
</xsd:schema>

=== SafirSDK/safir-sdk-core/src/dose/dose_test.ss/data/Unmigrated_Testcases.xml
<?xml version="1.0" encoding="utf-8"?>
<class xmlns="urn:safir-dots-unit" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:safir-dots-unit file:///c:/tower/syskt-3.0/runtime/data/text/dots/config/dots_unit.xsd">
  <name>DoseTest.Tests</name>
  <baseClass>Object</baseClass>
  <instances>0</instances>
  <parameters>
    <parameter>
      <name>TestCases</name>
      <type>DoseTest.Items.TestCase</type>
      <arrayElements>

        <!--  ++++++++++++++++++++++++++ ENTITIES ++++++++++++++++++++++++++ -->

        <!--0Test of registration of entity class (local)-->
        <!--  new tc 300 -->
        <!--1Test of registration of one entity instance (local)-->
        <!--  NOT VALID ANY MORE -->
        <!--2Test of registration and registration subscription (of one global instance)-->
        <!--  NOT VALID ANY MORE -->
        <!--3Test of registration and registration subscription (of one global class)-->
        <!--  new tc 301 -->
        <!--4Test of unsubscription of registrations (of global class)-->
        <!--  new tc 310 -->
        <!--5Test of whole class registration subscription. Class is registered whole class.  -->
        <!--  new tc 301 -->
        <!--6Test of whole class registration subscription. Class is registered per instance.  -->
        <!--  new tc 301 -->
        <!--7Test of instance registration subscription. Class is registered whole class.  -->
        <!--  NOT VALID ANY MORE -->
        <!--8Test of instance + whole class registration subscription. Class is registered whole class.  -->
        <!--  new tc 301 -->
        <!--9Test of whole class registration unsubscription (with previous instance subscriptions). -->
        <!--  new tc 302 -->
        <!--10Test that unsubscription of instance registration is a null operation when whole class subscription exist. -->
        <!--  new tc 303 -->
        <!--11Test that different consumers don't interfere. -->
        <!--  new tc 312 -->
        <!--12Test of registration subscription of superclasses-->
        <!--  new tc 309 -->
        <!--13Test of registration of two local instances at two different nodes-->
        <!--  new tc 311 -->
        <!--14Test of overriding registration of global instance (with override)-->
        <!--  new tc 354 (handlers replaces instances) -->
        <!--15Test of pending registration of global entity-->
        <!-- new tc 350  -->

        <!--16Test of registration revoke-->
        <!-- new tc 354  -->
        <!--17Testing IsRegistered function when one (local) instance is registered-->
        <!--  NOT VALID ANY MORE -->
        <!--18Testing IsRegistered function when one (local) class is registered-->
        <!--  NOT VALID ANY MORE -->


        <!--19Test of owner setting entity (local)-->
        <!-- new tc 400  -->
        <!--20Test of non-owner setting entity owned by another connection-->
        <!-- new tc 401  -->
        <!--21Test of non-owner setting unowned entity-->
        <!-- new tc 402  -->
        <!--22Test of owner deleting instance (global)-->
        <!-- new tc 403  -->
        <!--23Test of non-owner deleting entity within the same connection as owner-->
        <!-- new tc 404  -->
        <!--24Test of non-owner deleting entity owned by another connection-->
        <!-- new tc 405  -->
        <!--25Test of non-owner deleting unowned entity-->
        <!-- new tc 406  -->

        <!--26Test of entity subscription of local entity (without changeflags, with updates)-->
        <!-- new tc 451  -->
        <!--27Test of entity subscription of local entity (without changeflags, without updates)-->
        <!-- new tc 450  -->
        <!--28Test of entity subscription of local entity (with changeflags, with updates)-->
        <!-- new tc 451  -->
        <!--29Test of entity subscription of global entity (without changeflags, with updates)-->
        <!-- new tc 460  -->
        <!--30Test of entity subscription of global entity (without changeflags, without updates)-->
        <!-- new tc 459  -->
        <!--31Test of entity subscription of global entity (with changeflags, with updates)-->
        <!-- new tc 460  -->
        <!--32Test of subscription of entity superclass-->
        <!-- new tc 471  -->
        <!--33Test of unsubscription of global entity -->
        <!-- new tc 459  -->
        <!--34Test of unsubscription of global entity instance (after subscription of whole class) -->
        <!-- new tc 469  -->
        <!--35Test of creation flag -->
        <!-- new tc 470  -->

        <!--36Test of sending create request (owner on this node) -->
        <!-- new tc 500  -->
        <!--37Test of sending create request (owner on other node) -->
        <!-- new tc 501  -->
        <!--38Test of sending update request of non-created instance (owner on this node)-->
        <!-- new tc 502  -->
        <!--39Test of sending update request of created instance (owner on other node)-->
        <!-- new tc 503  -->
        <!--40Test of sending delete request of instance (owner on this node)-->
        <!-- new tc 505  -->
        <!--41Test of sending delete request of instance (owner on other node)-->
        <!-- new tc 506  -->
        <!--42Test of sending update request of unregistered instance(no owner)-->
        <!-- new tc 504  -->
        <!--43Test of entity request timeout (local request)-->
        <!-- new tc 508  -->
        <!--44Test of entity request timeout (global request)-->
        <!-- new tc 509  -->
        <!--45Test of entity request revoke (global request)-->
        <!--  NOT VALID ANY MORE -->
        <!--46Test of overflow notification while sending entity requests-->
        <!-- new tc 510  -->

        <!--47Test of GetNumberOfFreeInstances (one allocated instance, class registered by this connection)-->
        <!--  NOT VALID ANY MORE -->
        <!--48Test of GetNumberOfFreeInstances (one allocated instance, class registered by other connection)-->
        <!--  NOT VALID ANY MORE -->
        <!--49Test of GetFreeInstances (one allocated instance, class registered by this connection)-->
        <!--  NOT VALID ANY MORE -->
        <!--50Test of GetFreeInstance (one allocated instance, class registered by other connection)-->
        <!--  NOT VALID ANY MORE -->

        <!--51Test of ReadPrevious data during update (local)-->
        <arrayElement>
          <object>
            <name>DoseTest.Items.TestCase</name>
            <members>
              <member>
                <name>Description</name>
                <value>Testing that ReadPrevious on an object during update notification yields the data from the last update notification</value>
              </member>
              <member>
                <name>Expectation</name>
                <value>The read data should be "Set" and not "Updated"</value>
              </member>
              <member>
                <name>TestCaseSetupActions</name>
                <arrayElements>
                  <arrayElement>
                    <object>
                      <name>DoseTest.Action</name>
                      <instance>0</instance>
                      <members>
                        <member>
                          <name>ActionType</name>
                          <value>DoseTest.ActionEnum.RegisterEntity</value>
                        </member>
                        <member>
                          <name>ObjId</name>
                          <objectId>
                            <name>DoseTest.LocalEntity</name>
                          </objectId>
                        </member>
                        <member>
                          <name>OverrideRegistration</name>
                          <value>true</value>
                        </member>
                        <member>
                          <name>Consumer</name>
                          <value>1</value>
                        </member>
                      </members>
                    </object>
                  </arrayElement>
                  <arrayElement>
                    <object>
                      <name>DoseTest.Action</name>
                      <instance>0</instance>
                      <members>
                        <member>
                          <name>ActionType</name>
                          <value>DoseTest.ActionEnum.Set</value>
                        </member>
                        <member>
                          <name>Obj</name>
                          <object>
                            <name>DoseTest.LocalEntity</name>
                            <instance>0</instance>
                            <members>
                              <member>
                                <name>Info</name>
                                <value>Set</value>
                              </member>
                            </members>
                          </object>
                        </member>
                        <member>
                          <name>Consumer</name>
                          <value>1</value>
                        </member>
                      </members>
                    </object>
                  </arrayElement>
                  <arrayElement>
                    <object>
                      <name>DoseTest.Action</name>
                      <instance>0</instance>
                      <members>
                        <member>
                          <name>ActionType</name>
                          <value>DoseTest.ActionEnum.SubscribeEntity</value>
                        </member>
                        <member>
                          <name>ObjId</name>
                          <objectId>
                            <name>DoseTest.LocalEntity</name>
                            <instance>0</instance>
                          </objectId>
                        </member>
                        <member>
